# vodr_config.py
#
# Configurazione dedicata alla pipeline VODR. I valori arrivano dai notebook
# legacy VODR_HEAVY_PREP / TIME_PERCENTAGE / THRESHOLDS, ma sono isolati qui
# per evitare liste hardcoded nel notebook principale.

from copy import deepcopy


VODR_STATISTICS_CONFIGS = {
    33,
    49,
    50,
    51,
    52,
    53,
    54,
    56,
}

VODR_EXCLUDED_VINS = [
    "ZCFMG2AU20C548924",
    "ZCFMG2AU90C552985",
    "ZCFMG2AUX0C565955",
    "ZCFMG2AUX0C554437",
    "ZCFEG2RU70C544313",
    "ZCFMG2AU50C560064",
    "ZCFMG2AU30C565649",
]

DEFAULT_VODR_MT_CONFIGS = {
    260,
    286,
    287,
    288,
    290,
    300,
    301,
    302,
    303,
    304,
    307,
    310,
    311,
    312,
    315,
    317,
    319,
    323,
    325,
    327,
    328,
    329,
    330,
    335,
    336,
    339,
    367,
    368,
    371,
    372,
    373,
}

VODR_TO_MT_CONFIGS = {
    frozenset({5, 19}): {260, 288, 300, 301, 335, 336},
    frozenset({20, 21}): {286, 287, 302, 303, 335, 336},
    frozenset({22}): {290, 304, 339},
    frozenset({25, 27}): {307, 311, 315, 317, 319, 323, 325, 327, 328},
    frozenset({26, 28}): {310, 312, 329, 330},
    frozenset({32}): {367},
    frozenset({35, 36}): {368, 371},
    frozenset({37, 38}): {372, 373},
    frozenset({56}): {408},
    frozenset({25, 26, 27, 28}): {
        307,
        310,
        311,
        312,
        315,
        317,
        319,
        323,
        325,
        327,
        328,
        329,
        330,
    },
}

VODR_PERCENTAGE_GROUPS = {
    "1b": ["Ped1", "Ped2", "Ped3", "Ped4"],
    "2a": [
        "Weight7",
        "Weight20",
        "Weight25",
        "Weight30",
        "Weight40",
        "Weight45",
        "Weight50",
        "Weight55",
        "WeightFF",
    ],
    "2b": [
        "Veh2",
        "Veh20",
        "Veh50",
        "Veh80",
        "Veh86",
        "Veh90",
        "Veh96",
        "Veh100",
        "Veh150",
    ],
    "2c": [
        "ExTempmeno30",
        "ExTempmeno0",
        "ExTempmeno10",
        "ExTempmeno25",
        "ExTemp30",
        "ExTemp35",
        "ExTemp36",
    ],
    "3a": ["Brk1", "Brk2", "Brk3", "Brk4", "Brk5"],
    "3b": ["Ret110", "Ret50", "Ret15", "Ret0"],
    "3c": ["Retoil20", "Retoil100", "Retoil114"],
    "3d": ["Retw20", "Retw100", "Retw114"],
    "4a": [
        "GearR4",
        "GearR3",
        "GearR2",
        "GearR1",
        "GearN",
        "Gear1",
        "Gear2",
        "Gear3",
        "Gear4",
        "Gear5",
        "Gear6",
        "Gear7",
        "Gear8",
        "Gear9",
        "Gear10",
        "Gear11",
        "Gear12",
        "Gear13",
        "Gear14",
        "Gear15",
        "Gear16",
    ],
    "4c": [
        "TimeAutoWithVehicleMoving",
        "TimeSemiWithVehicleMoving",
        "TimeAutoSuspendWithVehicleMoving",
    ],
    "5a": [
        "Vbattmeno20",
        "Vbatt2023",
        "Vbatt2425",
        "Vbatt25",
        "Vbattmeno20IDLE",
        "Vbatt2023idle",
        "Vbatt2425idle",
        "Vbatt25idle",
        "Vbatt2531idle",
        "Vbatt31idle",
    ],
    "5b": [
        "Soc20OFF",
        "Soc2050OFF",
        "Soc5070OFF",
        "Soc7090OFF",
        "Soc100OFF",
        "Soc20ON",
        "Soc50ON",
        "Soc70ON",
        "Soc90ON",
        "Soc100ON",
    ],
    "5c": [
        "Soh20OFF",
        "Soh50OFF",
        "Soh70OFF",
        "Soh90OFF",
        "Soh100OFF",
        "Soh20ON",
        "Soh50ON",
        "Soh70ON",
        "Soh90ON",
        "Soh100ON",
    ],
    "6a": ["Crk700", "Crk1500", "Crkoltre1500"],
    "6b": ["Crkcur200", "Crkcur500", "Crkcur600", "Crkcuroltre600"],
    "6c": ["CrkVolt21", "CrkVolt23", "CrkVolt25", "CrkVoltoltre25"],
    "6d": [
        "Cur10",
        "Cur30",
        "Cur50",
        "Cur70",
        "Cur90",
        "Cur91",
        "Cureng10",
        "Cureng30",
        "Cureng50",
        "Cureng70",
        "Cureng90",
        "Cureng91",
    ],
}

VODR_REPORT_SHEETS = [
    {
        "sheet_id": "complete_dataset",
        "name": "Complete Dataset",
        "kind": "dataset",
    },
    {
        "sheet_id": "1b",
        "name": "1b Accelerator Pedal Position",
        "group_by": ["product_series", "product_model", "power", "vin"],
        "columns": VODR_PERCENTAGE_GROUPS["1b"],
        "triggers": [0, 0, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "1b_2",
        "name": "1b Accelerator Pedal Position 2",
        "source_sheet_id": "1b",
        "group_by": ["product_series", "product_model", "power", "mission"],
        "columns": VODR_PERCENTAGE_GROUPS["1b"],
        "triggers": [0, 0, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "1b_3",
        "name": "1b Accelerator Pedal Position 3",
        "source_sheet_id": "1b",
        "group_by": ["product_series", "product_type"],
        "columns": ["Ped4"],
        "triggers": [1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "2a",
        "name": "2a Vehicle Weight Time",
        "group_by": ["product_series", "product_model", "mission"],
        "columns": VODR_PERCENTAGE_GROUPS["2a"],
        "triggers": [0, 0, 0, 1, 1, 1, 1, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "2b",
        "name": "2b Vehicle Speed",
        "group_by": ["product_series", "power"],
        "columns": ["Veh2", "Veh96", "Veh100", "Veh150"],
        "triggers": [1, 1, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "2b_2",
        "name": "2b Vehicle Speed 2",
        "source_sheet_id": "2b",
        "group_by": ["product_series", "product_model", "power"],
        "columns": ["Veh2", "Veh96", "Veh100", "Veh150"],
        "triggers": [1, 1, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "2c",
        "name": "2c External Temperature",
        "group_by": ["product_series", "product_type"],
        "columns": VODR_PERCENTAGE_GROUPS["2c"],
        "triggers": [1, 1, 0, 0, 0, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "3a",
        "name": "3a Brake Pedal Position",
        "group_by": ["product_series", "power"],
        "columns": VODR_PERCENTAGE_GROUPS["3a"],
        "triggers": [0, 0, 0, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "3a_2",
        "name": "3a Brake Pedal Position 2",
        "source_sheet_id": "3a",
        "group_by": ["product_series", "product_model", "power"],
        "columns": VODR_PERCENTAGE_GROUPS["3a"],
        "triggers": [0, 0, 0, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "3b",
        "name": "3b Drive Retarder Torque",
        "group_by": ["product_series", "power"],
        "columns": VODR_PERCENTAGE_GROUPS["3b"],
        "triggers": [1, 1, 1, 0],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "3c",
        "name": "3c Retarder Oil Temperature",
        "group_by": ["product_series", "power"],
        "columns": VODR_PERCENTAGE_GROUPS["3c"],
        "triggers": [0, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "3d",
        "name": "3d Retarder Water Temperature",
        "group_by": ["product_series", "power"],
        "columns": VODR_PERCENTAGE_GROUPS["3d"],
        "triggers": [0, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "4a",
        "name": "4a Gear Shift",
        "group_by": ["product_series", "power", "mission"],
        "columns": VODR_PERCENTAGE_GROUPS["4a"],
        "triggers": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "4c",
        "name": "4c Transmission Mode",
        "group_by": ["product_series", "power", "mission"],
        "columns": VODR_PERCENTAGE_GROUPS["4c"],
        "triggers": [0, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "4c_2",
        "name": "4c Transmission Mode 2",
        "source_sheet_id": "4c",
        "group_by": ["product_series", "product_model", "power", "mission"],
        "columns": VODR_PERCENTAGE_GROUPS["4c"],
        "triggers": [0, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "5a",
        "name": "5a Battery Voltage",
        "group_by": ["product_series", "power", "mission"],
        "columns": VODR_PERCENTAGE_GROUPS["5a"],
        "triggers": [1, 1, 0, 0, 1, 1, 1, 0, 0, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "5b",
        "name": "5b Battery SOC",
        "group_by": ["product_series", "power", "mileage_range", "mission"],
        "columns": VODR_PERCENTAGE_GROUPS["5b"],
        "triggers": [1, 1, 1, 0, 0, 1, 1, 1, 0, 0],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "5c",
        "name": "5c Battery SOH",
        "group_by": ["product_series", "power", "mileage_range", "mission"],
        "columns": VODR_PERCENTAGE_GROUPS["5c"],
        "triggers": [1, 1, 1, 0, 0, 1, 1, 1, 0, 0],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "5c_2",
        "name": "5c Battery SOH 2",
        "source_sheet_id": "5c",
        "group_by": ["product_series", "power", "mileage_range"],
        "columns": ["Soh100ON"],
        "triggers": [0],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "6a",
        "name": "6a Cranking Time",
        "group_by": ["product_series", "power", "mileage_range", "mission"],
        "columns": VODR_PERCENTAGE_GROUPS["6a"],
        "triggers": [0, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "6b",
        "name": "6b Current during Cranking",
        "group_by": ["product_series", "power", "mileage_range", "mission"],
        "columns": VODR_PERCENTAGE_GROUPS["6b"],
        "triggers": [0, 1, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "6b_2",
        "name": "6b Current 2",
        "source_sheet_id": "6b",
        "group_by": ["product_series", "power", "mission"],
        "columns": VODR_PERCENTAGE_GROUPS["6b"],
        "triggers": [0, 1, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "6c",
        "name": "6c Voltage during Cranking",
        "group_by": ["product_series", "power", "mission"],
        "columns": VODR_PERCENTAGE_GROUPS["6c"],
        "triggers": [1, 1, 0, 0],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "6c_2",
        "name": "6c Voltage 2",
        "source_sheet_id": "6c",
        "group_by": ["product_series", "power", "mileage_range", "mission"],
        "columns": VODR_PERCENTAGE_GROUPS["6c"],
        "triggers": [1, 1, 0, 0],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "6d",
        "name": "6d Current measured",
        "group_by": ["product_series", "power", "mission"],
        "columns": VODR_PERCENTAGE_GROUPS["6d"],
        "triggers": [0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1],
        "use_percentage_columns": True,
    },
    {
        "sheet_id": "average_kick_down",
        "name": "2 Average Kick down",
        "group_by": ["product_series", "power"],
        "columns": ["AvgKickDown"],
        "triggers": [0],
        "use_percentage_columns": False,
    },
    {
        "sheet_id": "average_kick_down_2",
        "name": "2 Average Kick down 2",
        "group_by": ["product_series", "power", "mission"],
        "columns": ["AvgKickDown"],
        "triggers": [0],
        "use_percentage_columns": False,
    },
    {
        "sheet_id": "selection_mode",
        "name": "2 Selection Mode_%",
        "group_by": ["product_series", "power"],
        "columns": ["ECOModePerc", "PECCPreselectionPerc", "EcorollPerc", "ManualPerc", "CCPerc", "ACCPerc"],
        "triggers": [0, 0, 0, 1, 0, 0],
        "use_percentage_columns": False,
    },
    {
        "sheet_id": "selection_mode_2",
        "name": "2 Selection Mode_%_2",
        "group_by": ["product_series", "power", "mission"],
        "columns": ["ECOModePerc", "PECCPreselectionPerc", "EcorollPerc", "ManualPerc", "CCPerc", "ACCPerc"],
        "triggers": [0, 0, 0, 1, 0, 0],
        "use_percentage_columns": False,
    },
    {
        "sheet_id": "time_in_semi",
        "name": "2 Time in semi %",
        "group_by": ["product_series", "product_type"],
        "columns": [
            "TimeInSemiWithEngineRunning",
            "TimeInAutoSuspendWithEngineRunning",
            "TimeInAutoWithEngineRunning",
        ],
        "triggers": [1, 1, 0],
        "use_percentage_columns": False,
    },
    {
        "sheet_id": "aebs_intervention",
        "name": "2 AEBS Intervention",
        "group_by": ["product_series", "power", "mission"],
        "columns": ["TotNumAEBSevents"],
        "triggers": [1],
        "use_percentage_columns": False,
    },
    {
        "sheet_id": "safety",
        "name": "3 Safety",
        "group_by": ["product_series", "power", "mileage_range"],
        "columns": ["ASRBrakeact", "ABSact", "ROPEngineCtrl", "ROPBrakeCtrl", "YCengine", "YCbrake", "ASRengact"],
        "triggers": [1, 1, 1, 1, 1, 1, 1],
        "use_percentage_columns": False,
    },
    {
        "sheet_id": "level",
        "name": "5 Level",
        "group_by": ["product_series", "power", "mileage_range"],
        "columns": ["CoolantLevLow", "OilLevLow"],
        "triggers": [1, 1],
        "use_percentage_columns": False,
    },
    {
        "sheet_id": "lights",
        "name": "6 Lights",
        "group_by": ["product_series", "mileage_range"],
        "columns": [
            "TimeBedSpotlight",
            "TimeSteplight",
            "TimeFpositionsx",
            "TimeFpositiondx",
            "TimeDRLight",
            "TimeWorkLight",
            "TimeCentralight",
            "TimeSidelight",
            "TimeRPositionsx",
            "TimeRPositiondx",
            "TimeCeiling",
            "TimeFrontMarker",
            "TimeRearMarker",
            "TimeLicenseplate",
            "TimeReverse",
            "TimeStopsx",
            "TimeStopdx",
            "TimeRfog",
            "TimeAddLight",
            "TimeFfogsx",
            "TimeFfogdx",
            "TimeRearTlightsx",
            "TimeRearTlightdx",
            "TimeFLsx",
            "TimeFLdx",
            "Timehighbeamsx",
            "Timehighbeamdx",
            "TimeLowbeamLightsx",
            "TimeLowbeamLightdx",
        ],
        "triggers": [1] * 29,
        "use_percentage_columns": False,
    },
]


def config_mt_from_vodr(config):
    """Restituisce le config Mission Test collegate alle config VODR."""
    normalized = frozenset(int(value) for value in config)
    return set(VODR_TO_MT_CONFIGS.get(normalized, DEFAULT_VODR_MT_CONFIGS))


def get_vodr_percentage_groups(config):
    """Restituisce i gruppi percentuali, con la variante storica per config 5/19."""
    groups = deepcopy(VODR_PERCENTAGE_GROUPS)
    if set(config) == {5, 19}:
        groups["4c"] = ["TimeAuto", "TimeSemi", "TimeAutoSuspendWithVehicleMoving"]
    return groups


def get_vodr_report_sheets(config=None):
    """Restituisce la configurazione sheet VODR."""
    sheets = deepcopy(VODR_REPORT_SHEETS)
    if config is not None and set(config) == {5, 19}:
        for sheet in sheets:
            if sheet.get("source_sheet_id", sheet["sheet_id"]) == "4c":
                sheet["columns"] = ["TimeAuto", "TimeSemi", "TimeAutoSuspendWithVehicleMoving"]
    return sheets


def generated_percentage_column(column_name, sheet_id):
    """Nome colonna creato da engine_stats.pyspark_variabili_x."""
    return f"{column_name.upper()}_{sheet_id.upper()}"


def get_vodr_export_file_name(config):
    config_str = "_".join(map(str, sorted(int(value) for value in config)))
    return f"VODR_{config_str}_new_thresholds.xlsx"
